### ISSUE TITLE
When generating data using the code in Baidu network disk, a warning appears

### ISSUE THREAD

**Issue by zdyshine** [RyanXingQL/STDF-PyTorch#1]
Thank you for sharing the project, when I use the code in Baidu Netdisk to generate data, it appears:
generating cfg...
18 videos found.
> done.
1/18: compressing BQMall_832x480_600...
2/18: compressing BQSquare_416x240_600...
3/18: compressing BQTerrace_1920x1080_600...
4/18: compressing BasketballDrill_832x480_500...
5/18: compressing BasketballDrive_1920x1080_500...
6/18: compressing BasketballPass_416x240_500...
7/18: compressing BlowingBubbles_416x240_500...
8/18: compressing Cactus_1920x1080_500...
9/18: compressing FourPeople_1280x720_600...
10/18: compressing Johnny_1280x720_600...
11/18: compressing Kimono_1920x1080_240...
12/18: compressing KristenAndSara_1280x720_600...
13/18: compressing ParkScene_1920x1080_240...
14/18: compressing PartyScene_832x480_500...
15/18: compressing PeopleOnStreet_2560x1600_150...
16/18: compressing RaceHorses_416x240_300...
17/18: compressing RaceHorses_832x480_300...
18/18: compressing Traffic_2560x1600_150...
******************************************************************
** WARNING: --SEIDecodedPictureHash is now disabled by default. **
**          Automatic verification of decoded pictures by a     **
**          decoder requires this option to be enabled.         **
******************************************************************
******************************************************************
** WARNING: --SEIDecodedPictureHash is now disabled by default. **
**          Automatic verification of decoded pictures by a     **
**          decoder requires this option to be enabled.         **
******************************************************************
******************************************************************
** WARNING: --SEIDecodedPictureHash is now disabled by default. **
**          Automatic verification of decoded pictures by a     **
**          decoder requires this option to be enabled.         **
******************************************************************
******************************************************************
** WARNING: --SEIDecodedPictureHash is now disabled by default. **
**          Automatic verification of decoded pictures by a     **
**          decoder requires this option to be enabled.         **
******************************************************************
******************************************************************
** WARNING: --SEIDecodedPictureHash is now disabled by default. **
**          Automatic verification of decoded pictures by a     **
**          decoder requires this option to be enabled.         **
******************************************************************
******************************************************************
** WARNING: --SEIDecodedPictureHash is now disabled by default. **
**          Automatic verification of decoded pictures by a     **
******************************************************************
******************************************************************
**          decoder requires this option to be enabled.         **
** WARNING: --SEIDecodedPictureHash is now disabled by default. **
** WARNING: --SEIDecodedPictureHash is now disabled by default. **
**          Automatic verification of decoded pictures by a     **
******************************************************************
**          decoder requires this option to be enabled.         **
**          Automatic verification of decoded pictures by a     **
******************************************************************
**          decoder requires this option to be enabled.         **
******************************************************************
 How can I solve this? Does it have any impact on data usage?

**Comment by ryanxingql** [comment]
Hi
You may first check if the compressed videos are generated without error (e.g., check the generated log files, or watch videos directly).
If the videos are successfully generated, then you can ignore these warnings.
Otherwise, you may better show me the generated log files and let me check what happened.
Thx
