### ISSUE TITLE
Dropbox dataset not available

### ISSUE THREAD

**Issue by gulzainali98** [RyanXingQL/STDF-PyTorch#12]
Dataset in dropbox is not available. However, I am not sure how to download the baidu pan dataset directly to my server.

**Comment by gulzainali98** [comment]
It's necessary for me because i have to download the data directly to my cluster

**Comment by RyanXingQL** [comment]
Hi gulzainali98, sorry for my late response.
The Dropbox link is now available~

**Comment by ryanxingql** [comment]
Hi gulzainali98, sorry for my late response.
I will fix it in one day.

**Comment by gulzainali98** [comment]
Thank you for responding. 

I needed the dataset for a project I am working on..... would be great if this can get resolved as soon as possible :) 

Thank you very much. Or maybe you can provide any other option. Maybe google drive :/

**Comment by ryanxingql** [comment]
Sorry for my late response.
The Dropbox subscription is out-of-date now and I will fix it in one day.
I will also contact you as soon as I finish it.
Sorry again.

**Comment by ryanxingql** [comment]
Hi gulzainali98!
A specialized team from Dropbox is helping us to fix it. It may take 24 hours. Sorry for your inconvenience.
As soon as it is okay, I will contact you.

**Comment by gulzainali98** [comment]
hello, 
Okay looking forward to your response :)

**Comment by ryanxingql** [comment]
Hi,
The former Dropbox link is broken.
I create a new [link](https://www.dropbox.com/sh/j4g5jsip8o9sr3x/AABP481b_E30DtMLUTudVYJsa?dl=0) and I am still uploading files to this link, which may take about 48 hours.
Sorry for your inconvenience.
When I finish uploading, I will inform you.

**Comment by ryanxingql** [comment]
Hi, you can download the data-set from the new Dropbox link now!

**Comment by gulzainali98** [comment]
Hey Sorry for late response. I can download the dataset. Thank you very much. 
However, do you know if the video encoder can be used to simply compress set of images instead of a video?

**Comment by ryanxingql** [comment]
You can check here: https://github.com/RyanXingQL/PowerQE#2-image-data
I suggest using the BPG encoder.

**Comment by gulzainali98** [comment]
BPG will result same compression artifacts as HVEC? Can I replace HVEC with BPG and train your network on this data?

**Comment by ryanxingql** [comment]
BPG adopts the All Intra (AI) mode of HEVC. In MFQE and STDF papers, LDP mode is considered. The AI and LDP modes are different, so as the resulting compression artifacts.

**Comment by gulzainali98** [comment]
I can create a video out of images but when can't seem to extract frames from the compressed video. I use opencv I420 to create a yuv video from the frames and then use encoder provided to compress it and then i want to extract the frames from this compressed video.

**Comment by gulzainali98** [comment]
rgb frames*

**Comment by gulzainali98** [comment]
i was able to extract the frames. Do you use I420 yuv videos in MFQE dataset?

**Comment by ryanxingql** [comment]
YUV 420P format.

**Comment by gulzainali98** [comment]
Any idea how to use HEVC on custom width and height? I am getting following error
`Resulting coded frame width must be a multiple of the minimum CU size`

**Comment by ryanxingql** [comment]
You can first pad the input frame, and make sure that the new height and width are a multiple of 16. After compression, you can crop the input frame back with the original resolution.

**Comment by gulzainali98** [comment]
yes. Thank you very much. perfect solution (y)

**Comment by gulzainali98** [comment]
still HEVC not working
my frame size in videos is (48, 64, 3).... could it be that the frame size is too small?

**Comment by ryanxingql** [comment]
You can try 64 instead of 16.

**Comment by gulzainali98** [comment]
compressing videos is taking forever, can you please share your compressed videos?
