### ISSUE TITLE
Request to share compressed video

### ISSUE THREAD

**Issue by gulzainali98** [RyanXingQL/STDF-PyTorch#13]
compressing videos is taking forever, can you please share your compressed videos?

**Comment by ryanxingql** [comment]
I am sorry gulzainali98, I don't have the compressed videos in my PC.

The HM codec is a standard codec without any speed-up optimization. If you want to get compressed videos with similar quality (usually lower than that of HM output) in a much faster speed, you can use FFmpeg.
