### ISSUE TITLE
docker environment

### ISSUE THREAD

**Issue by doudoublues** [RyanXingQL/STDF-PyTorch#16]
I'm trying to build the dcnv2 ops but always failed, could you give me a docker image file？

**Comment by ryanxingql** [comment]
Sorry I don't have docker file.
Please refer to the official dcnv2 repository.

My version:
Ubuntu 20.04
CUDA 10.1
GCC 9.3.0
Python 3.7
PyTorch 1.6.0
ninja 1.10.0

**Comment by doudoublues** [comment]
thx！



---Original---
From: "Qunliang ***@***.***&gt;
Date: Fri, Dec 3, 2021 13:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RyanXingQL/STDF-PyTorch] docker environment (Issue #16)




 
Sorry I don't have docker file.
 
My version:
 Ubuntu 20.04
 CUDA 10.1
 GCC 9.3.0
 Python 3.7
 PyTorch 1.6.0
 ninja 1.10.0
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
