### ISSUE TITLE
About batchsize

### ISSUE THREAD

**Issue by doudoublues** [RyanXingQL/STDF-PyTorch#17]
Hello Ryan，why batchsize==32？ Because I notice that if i use 4 GPUs , maybe only 2~3GB memory is used on each GPU.  Can I make batchsize or patch size(like 256 * 256 ) larger  and will it decrease the performance?

**Comment by ryanxingql** [comment]
Hi,
I haven't tried. I guess the performance will not decrease, unless you use a small data-set.

**Comment by doudoublues** [comment]
thx
