### ISSUE TITLE
How to visualize the offsets in each frame as Fig 3 in the paper?

### ISSUE THREAD

**Issue by zzwei1** [RyanXingQL/STDF-PyTorch#2]
Nice work!
I wonna know how to visualize the offsets in each frame as Fig 3 in the paper, is there some guidiance?
![image](https://user-images.githubusercontent.com/49705380/102569034-b3b97700-411f-11eb-878e-9098f8148145.png)

**Comment by ryanxingql** [comment]
Hi!

Unfortunately, I am not the author of this work. I just implement it by my own.
For accurate details, you can email the author Jianing Deng. He is really a nice guy hhh.

In my opinon, the offset is explicitly learned in our network:
https://github.com/RyanXingQL/STDF-PyTorch/blob/9acce89fe2adfbfd6a1783c2d9f48c30dc4988bb/net_stdf.py#L99
So you can simply visualize the learned feature map here.

**Comment by zzwei1** [comment]
> Hi!
> 
> Unfortunately, I am not the author of this work. I just implement it by my own.
> For accurate details, you can email the author Jianing Deng. He is really a nice guy hhh.
> 
> In my opinon, the offset is explicitly learned in our network:
> https://github.com/RyanXingQL/STDF-PyTorch/blob/9acce89fe2adfbfd6a1783c2d9f48c30dc4988bb/net_stdf.py#L99
> 
> 
> So you can simply visualize the learned feature map here.

Thanks for your guidiance! I 'll try it!
