### ISSUE TITLE
a question of cuda out of memory in test one video

### ISSUE THREAD

**Issue by LHL731** [RyanXingQL/STDF-PyTorch#20]
您好，当我使用一个视频进行测试时，我用416*240与832*480的yuv序列进行测试的时候没有问题，但使用更高分辨率的yuv序列进行测试的时候就会爆显存，我有看到训练的时候会裁剪成128*128的，但是对一个视频进行测试的时候为了更好的显示增强结果就没有进行图片裁剪，想问问您是怎么解决这个问题的呢

**Comment by ryanxingql** [comment]
您好 目前框架确实存在这个问题，包括BasicVSR++也是

**Comment by ryanxingql** [comment]
您好，目前框架确实存在这一问题，例如BasicVSR++也一样

我建议通过切块的方法做。代码和示例可以参考这里：
https://gist.github.com/ryanxingql/e126eeb0d2e156bcfe28bc532143d82e

块可以在显存允许的情况下尽量大一些，减少对性能的影响。
