### ISSUE TITLE
flops of deformable convolution

### ISSUE THREAD

**Issue by kepengxu** [RyanXingQL/STDF-PyTorch#21]
thank you for your release project!
Is there any reference document or code for the flops calculation method of deformable convolution?

**Comment by ryanxingql** [comment]
Hi, I use [pytorch-OpCounter](https://github.com/Lyken17/pytorch-OpCounter) in another [work](https://github.com/ryanxingql/rbqe/blob/34c961d4df7dea3882297601836b245d0b552739/main_test.py).
