### ISSUE TITLE
how to visualize the enhanced yuv data

### ISSUE THREAD

**Issue by doudoublues** [RyanXingQL/STDF-PyTorch#22]
thanks for your work!, After inference, the y-channel has been enhanced, I want to know how to visualize the enhanced y-channel with origin U,V data by transforming them to RGB data?

**Comment by ryanxingql** [comment]
Hi,
You may use this code:
https://github.com/ryanxingql/pythonutils/blob/09f6795c2d686bf1f4e9ce904ff9e134438ceab7/conversion.py#L172
to convert YUV420P to YUV444P.

Then convert this YUV444P image to RGB.

**Comment by doudoublues** [comment]
thanks!
