### ISSUE TITLE
about vimeo 90k dataset

### ISSUE THREAD

**Issue by doudoublues** [RyanXingQL/STDF-PyTorch#23]
why use all-intra mode to compress data? In this case, all frames have same quality, is it useful to use neighbor frames' information?

**Comment by ryanxingql** [comment]
Yes it is better to use LDP mode. It is my mistake.
The MFQEv2 dataset is correctly compressed by LDP.

**Comment by doudoublues** [comment]
can i just use the same process pipeline as MFQEv2 dataset to compressed the vimeo90k data?

**Comment by ryanxingql** [comment]
Yes for sure. Note that you may first have to convert the Vimeo90K images into sequences (videos).

**Comment by doudoublues** [comment]
thx very much!
