### ISSUE TITLE
关于deform_conv的一些问题

### ISSUE THREAD

**Issue by wangweiran970922** [RyanXingQL/STDF-PyTorch#25]
您好，我遇到了一些关于可变性卷积的问题，想向您请教一下。
我注意到您在net_stdf.py中应用deform_conv中的输入是Y通道也就是1通道的信息。
这种情况下如果输入是RGB的图像的话，请问需要修改哪些参数呢？
期待您的回复，非常感谢！

**Comment by ryanxingql** [comment]
请参考这里的做法：https://github.com/ryanxingql/powerqe/blob/v3/powerqe/models/backbones/stdf.py
