### ISSUE TITLE
关于保存结果的一些相关咨询

### ISSUE THREAD

**Issue by wangweiran0922** [RyanXingQL/STDF-PyTorch#26]
您好，我在使用您发布的预训练模型进行测试时，发现仅有Y通道的结果与指标。
请问这种情况下，想保留png格式的结果图应该如何操作与修改呢？
希望可以得到您的帮助，万分感谢。

**Comment by ryanxingql** [comment]
https://github.com/ryanxingql/stdf-pytorch/issues/19

**Comment by wangweiran0922** [comment]
非常感谢
