### ISSUE TITLE
Detail about training

### ISSUE THREAD

**Issue by linjing7** [RyanXingQL/STDF-PyTorch#5]
Hi, thank you very much for your excellent work. I have some question about the training: 
1. There is only one pretrained model you provided. Which QP is it respond to? Is QP=37?
2.  It seems that the result (QP=37?) you provided is a little lower than the paper: 0.778dB VS 0.83dB. Is it caused by the difference of the training dataset ? 
3. In the paper STDF, when comparing with other video quality enhancement methods, the author did not retrained them in the same dataset, do you think it may not fair?

**Comment by ryanxingql** [comment]
Hi
1. Yes. BTW I'm not the author of this paper. I re-trained QP=37 model, and then open-sourced it.
2. My reproduced model is STDF-R3, not R3L. My reproduced result is 0.778 dB, which is slighly higher than the reported result 0.75 dB.
3. Some reviewers think that all compared approaches should be re-trained over the same dataset. However, to some reviewers, the generalization ability is also an attribute of an approach. Therefore, the author may not need to re-train the compared approach.

**Comment by linjing7** [comment]
Okay, thank you very much for your reply.
