### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by linjing7** [RyanXingQL/STDF-PyTorch#7]
Hi, I have met some problems during  training. 
1. As metioned in the last issue, I have made YUV lmdb instead of Y lmdb. However, when I use it as training set, it takes much longer time than origin method, about 2 times. I think it may be caused by the _cv2.imdecode()_ function. I fould that when making lmdb, we use the _cv2.imencode()_ with compression level as 1, therefore, we need to decode while reading data from lmdb. I would like to  skip the _cv2.imencode()_ while making lmdb, that is, save the data into lmdb without compression,  in this way I don't need to use _cv2.imdecode()_ function during training, which may save some time. I wonder that if this will make influence on the final result?
2. BTY, you have mentioned in the Q&A that you enlarge the dataset by 'set sampling index = target index % dataset len'. I don't understand it, could you please tell me where it is in the code?

**Comment by ryanxingql** [comment]
1. I don't know. You can have a try and set the compression level being 0, which means no compression.
2. https://github.com/RyanXingQL/STDF-PyTorch/blob/36a6adfe0c33f030a68155eb706326d4ee896027/utils/deep_learning.py#L86

**Comment by linjing7** [comment]
Okay, thank you very much, I will have a try.
